//! Zola index composition translated from MIT-licensed Hunk generate-changelog.ts.
//! Copyright (c) Modem Labs Inc. See THIRD_PARTY_NOTICES.
use super::*;
use std::collections::BTreeMap;

fn render(
    series: &[ReleaseSeries],
    notes: &BTreeMap<String, Note>,
    dates: &BTreeMap<String, String>,
) -> String {
    let mut metadata = toml_edit::DocumentMut::new();
    metadata["title"] = toml_edit::value("Changelog");
    metadata["description"] = toml_edit::value(
        "Every Workdeck release, newest first — features, fixes, and performance work in the terminal diff viewer.",
    );
    metadata["path"] = toml_edit::value("changelog/");
    let mut lines = vec!["+++".into(), metadata.to_string().trim_end().into(), "+++".into(), String::new(), "<!-- Generated by cargo xtask changelog index; do not edit by hand. -->".into(), String::new(), "[RSS](https://workdeck.dev/changelog/rss.xml) · [CHANGELOG.md](https://github.com/ruttydm/workdeck/blob/main/CHANGELOG.md)".into(), String::new()];
    let latest = series
        .iter()
        .find(|s| s.releases.iter().any(|r| is_stable_published(r, dates)))
        .map(|s| &s.minor);
    for series in series {
        let span = series_span(series, dates);
        let published: Vec<_> = series
            .releases
            .iter()
            .filter(|r| is_published(r, dates))
            .collect();
        let prerelease_only = !published.is_empty() && published.iter().all(|r| r.prerelease);
        let mut meta = Vec::new();
        if latest == Some(&series.minor) {
            meta.push("Latest".to_owned());
        }
        if prerelease_only {
            meta.push("Prerelease".into());
        } else if span.is_none() {
            meta.push("Unreleased".into());
        }
        if let Some(span) = span {
            meta.push(span);
        }
        let count = series.releases.len();
        let changes: usize = series
            .releases
            .iter()
            .flat_map(|r| &r.sections)
            .map(|s| s.entries.len())
            .sum();
        meta.push(format!(
            "{count} release{}",
            if count == 1 { "" } else { "s" }
        ));
        meta.push(format!(
            "{changes} change{}",
            if changes == 1 { "" } else { "s" }
        ));
        lines.extend([
            format!(
                "## [Workdeck {}](/changelog/{}/)",
                series.minor, series.minor
            ),
            String::new(),
            meta.join(" · "),
            String::new(),
        ]);
        if let Some(summary) = series_summary(
            series,
            notes.get(&series.minor).and_then(|n| n.summary.as_deref()),
        )
        .filter(|s| !s.is_empty())
        {
            lines.extend([
                truncate_description(&to_plain_text(&summary), 240),
                String::new(),
            ]);
        }
    }
    format!(
        "{}\n",
        regex::Regex::new(r"\n{3,}")
            .unwrap()
            .replace_all(&lines.join("\n"), "\n\n")
            .trim_end_matches(ecmascript_whitespace)
    )
}

#[derive(serde::Deserialize)]
struct Note {
    summary: Option<String>,
}

pub(in crate::changelog) fn run_index(
    repo: &Path,
    mut args: impl Iterator<Item = String>,
) -> Result<()> {
    let Some(markdown) = args.next() else {
        bail!("changelog index requires Markdown and dates JSON files");
    };
    let Some(dates) = args.next() else {
        bail!("changelog index requires Markdown and dates JSON files");
    };
    let notes = args.next();
    if args.next().is_some() {
        bail!("changelog index accepts Markdown, dates JSON and optional notes JSON files");
    }
    let notes = match notes {
        Some(path) => serde_json::from_str(&std::fs::read_to_string(repo.join(path))?)?,
        None => BTreeMap::new(),
    };
    let dates = serde_json::from_str(&std::fs::read_to_string(repo.join(dates))?)?;
    let series = group_into_series(parse_changelog(&std::fs::read_to_string(
        repo.join(markdown),
    )?));
    print!("{}", render(&series, &notes, &dates));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_body_matches_pinned_publication_oracles() {
        let fixture: serde_json::Value = serde_json::from_str(include_str!(
            "../../../../port/hunk/website-changelog-index-oracle.json"
        ))
        .unwrap();
        let results = fixture["results"].as_array().unwrap();
        assert_eq!(results.len(), 2);
        for (i, result) in results.iter().enumerate() {
            let cases = result["cases"].as_array().unwrap();
            assert_eq!(cases.len(), [4, 2][i]);
            for case in cases {
                let series = group_into_series(parse_changelog(case["input"].as_str().unwrap()));
                let notes = serde_json::from_value(case["notes"].clone()).unwrap();
                let dates = serde_json::from_value(case["dates"].clone()).unwrap();
                let page = render(&series, &notes, &dates);
                let expected = case["expected"]
                    .as_str()
                    .unwrap()
                    .replace("Hunk", "Workdeck")
                    .replace("https://hunk.dev", "https://workdeck.dev")
                    .replace(
                        "https://github.com/modem-dev/hunk",
                        "https://github.com/ruttydm/workdeck",
                    );
                // Zola frontmatter and the generator notice are intentionally migrated.
                // Compare the entire reader-visible Markdown body without normalization.
                if i == 1 {
                    // Stable omits prereleases from the count even when unpublished.
                    // Preserve this superseded behavior as explicit differential evidence.
                    assert!(expected.contains("Unreleased · 0 releases · 1 change"));
                    assert!(!page.contains("Unreleased · 0 releases · 1 change"));
                    assert_ne!(
                        &page[page.find("[RSS]").unwrap()..],
                        &expected[expected.find("[RSS]").unwrap()..]
                    );
                    continue;
                }
                assert_eq!(
                    &page[page.find("[RSS]").unwrap()..],
                    &expected[expected.find("[RSS]").unwrap()..]
                );
            }
        }
    }

    #[test]
    fn index_preserves_source_sample_content_in_zola_page() {
        let series = group_into_series(parse_changelog(include_str!(
            "../../../../port/hunk/website-changelog-test-sample.md"
        )));
        let dates = BTreeMap::from([
            ("0.19.0".into(), "2026-08-16".into()),
            ("0.18.0".into(), "2026-08-08".into()),
            ("0.15.3".into(), "2026-06-13".into()),
        ]);
        let page = render(&series, &BTreeMap::new(), &dates);
        assert_eq!(page.matches("Latest ·").count(), 1);
        assert!(page.contains("Latest · August 16, 2026 · 2 releases · 3 changes"));
        assert!(!page.contains("Release notes for Workdeck 0.15:"));
        let intro = page
            .split("+++")
            .nth(2)
            .unwrap()
            .split("## ")
            .next()
            .unwrap();
        assert!(intro.contains("[RSS](https://workdeck.dev/changelog/rss.xml)"));
        assert!(intro.contains("CHANGELOG.md"));
        assert!(!intro.contains("newest first"));
        for minor in ["0.19", "0.18", "0.15"] {
            assert!(page.contains(&format!("## [Workdeck {minor}](/changelog/{minor}/)")));
        }
        let metadata = page
            .split("+++")
            .nth(1)
            .unwrap()
            .parse::<toml_edit::DocumentMut>()
            .unwrap();
        assert_eq!(metadata["path"].as_str(), Some("changelog/"));
    }
}
