//! Workdeck/Zola composition of the MIT-licensed Hunk release page sections.
//! Copyright (c) Modem Labs Inc. See THIRD_PARTY_NOTICES.

use super::*;
use std::collections::BTreeMap;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn page_composes_sections_and_zola_metadata_without_npm() {
        let series = group_into_series(parse_changelog(
            "## 1.2.0\n### Highlights\nA lead.\n\n- Detail.\n### Fixed\n- Fix.\n",
        ))
        .pop()
        .unwrap();
        let notes: Notes = serde_json::from_value(serde_json::json!({"video":{"mp4":"/v.mp4","title":"keep is:inline"},"links":[{"label":"Docs","href":"/docs/"}]})).unwrap();
        let dates = BTreeMap::from([("1.2.0".into(), "2026-08-16".into())]);
        let page = render_page(
            &series,
            &notes,
            &dates,
            Some("1.3"),
            Some("1.1"),
            Some("1.2.0"),
        )
        .unwrap();
        let metadata = page
            .split("+++")
            .nth(1)
            .unwrap()
            .parse::<toml_edit::DocumentMut>()
            .unwrap();
        assert_eq!(metadata["title"].as_str(), Some("Workdeck 1.2"));
        assert_eq!(metadata["path"].as_str(), Some("changelog/1.2/"));
        assert_eq!(page.matches("\nA lead.\n").count(), 1);
        assert!(page.contains("## Highlights\n\n- Detail."));
        assert!(page.contains("## Related documentation\n\n- [Docs](/docs/)"));
        assert!(page.contains("## Releases in this series"));
        assert!(page.contains("--tag v1.2.0 --package workdeck-cli --locked"));
        assert!(page.contains("workdeck update"));
        assert!(!page.contains("npm"));
        assert!(page.contains("keep is:inline"));
        assert!(page.contains("<script type=\"application/ld+json\">"));
        assert!(page.contains("[Newer: Workdeck 1.3]"));
        assert!(page.contains("[Older: Workdeck 1.1]"));
    }

    #[test]
    fn prerelease_and_unpublished_pages_have_no_install_command() {
        let series = group_into_series(parse_changelog("## 1.2.0-beta.1\n"))
            .pop()
            .unwrap();
        for dates in [
            BTreeMap::new(),
            BTreeMap::from([("1.2.0-beta.1".into(), "2026-08-16".into())]),
        ] {
            let page = render_page(&series, &Notes::default(), &dates, None, None, None).unwrap();
            assert!(!page.contains("cargo install"));
            assert!(!page.contains("workdeck update"));
            assert!(page.contains(if dates.is_empty() {
                "Unreleased · 1 release"
            } else {
                "Prerelease · August 16, 2026 · 1 release"
            }));
        }
    }
}

#[derive(Default, serde::Deserialize)]
pub(super) struct Notes {
    summary: Option<String>,
    video: Option<ReleaseVideo>,
    links: Option<Vec<Link>>,
}

#[derive(serde::Deserialize)]
struct Link {
    label: String,
    href: String,
}

pub(super) fn render_page(
    series: &ReleaseSeries,
    notes: &Notes,
    dates: &BTreeMap<String, String>,
    newer: Option<&str>,
    older: Option<&str>,
    latest: Option<&str>,
) -> Result<String> {
    let editorial = series_summary(series, notes.summary.as_deref());
    let summary = resolve_summary(series, notes.summary.as_deref(), dates, "Workdeck");
    let description = truncate_description(&to_plain_text(&summary), 155);
    let mut frontmatter = toml_edit::DocumentMut::new();
    frontmatter["title"] = toml_edit::value(format!("Workdeck {}", series.minor));
    frontmatter["description"] = toml_edit::value(description);
    frontmatter["path"] = toml_edit::value(format!("changelog/{}/", series.minor));
    let mut lines = vec![
        "+++".into(),
        frontmatter.to_string().trim_end().into(),
        "+++".into(),
        String::new(),
        "<!-- Generated by cargo xtask changelog pages; do not edit by hand. -->".into(),
        String::new(),
    ];
    let installable = series
        .releases
        .iter()
        .find(|r| is_stable_published(r, dates));
    let prerelease_only =
        installable.is_none() && series.releases.iter().any(|r| is_published(r, dates));
    let count = series.releases.len();
    lines.push(format!(
        "{}{} · {count} release{}",
        if prerelease_only {
            "Prerelease · "
        } else {
            ""
        },
        series_span(series, dates).unwrap_or_else(|| "Unreleased".into()),
        if count == 1 { "" } else { "s" }
    ));
    lines.push(String::new());
    if let Some(summary) = editorial {
        lines.extend([summary, String::new()]);
    }
    if let Some(video) = &notes.video {
        lines.extend([
            render_video(
                video,
                &series.minor,
                &to_plain_text(&summary),
                "Workdeck",
                "https://workdeck.dev",
            )
            .replacen(
                "<script type=\"application/ld+json\" is:inline>",
                "<script type=\"application/ld+json\">",
                1,
            ),
            String::new(),
        ]);
    }
    if let Some(release) = installable {
        lines.extend(["```sh".into(), format!("cargo install --git https://github.com/ruttydm/workdeck --tag v{} --package workdeck-cli --locked", release.version), "```".into(), String::new()]);
        if latest == Some(release.version.as_str()) {
            lines.extend([
                "This is the current release. Already installed? Use the update workflow for your installation:".into(),
                String::new(),
                "```sh".into(),
                "workdeck update".into(),
                "```".into(),
                String::new(),
            ]);
        } else {
            lines.extend([format!("Workdeck {} is no longer the current release. See [the latest release](/changelog/).", series.minor), String::new()]);
        }
    }
    if let Some(body) = series
        .releases
        .iter()
        .find_map(|r| r.highlights.as_deref())
        .and_then(|text| split_highlights(text).body)
    {
        lines.extend(["## Highlights".into(), String::new(), body, String::new()]);
    }
    if let Some(links) = notes.links.as_ref().filter(|links| !links.is_empty()) {
        lines.extend(["## Related documentation".into(), String::new()]);
        lines.extend(
            links
                .iter()
                .map(|link| format!("- [{}]({})", link.label, link.href)),
        );
        lines.push(String::new());
    }
    lines.push(render_release_body(
        series,
        dates,
        "https://github.com/ruttydm/workdeck",
    ));
    let mut around = Vec::new();
    if let Some(minor) = newer {
        around.push(format!("[Newer: Workdeck {minor}](/changelog/{minor}/)"));
    }
    if let Some(minor) = older {
        around.push(format!("[Older: Workdeck {minor}](/changelog/{minor}/)"));
    }
    around.push("[All releases](/changelog/)".into());
    lines.extend([
        "---".into(),
        String::new(),
        around.join(" · "),
        String::new(),
    ]);
    static BLANKS: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"\n{3,}").unwrap());
    Ok(format!(
        "{}\n",
        BLANKS
            .replace_all(&lines.join("\n"), "\n\n")
            .trim_end_matches(ecmascript_whitespace)
    ))
}

pub(in crate::changelog) fn run_pages(
    repo: &Path,
    mut args: impl Iterator<Item = String>,
) -> Result<()> {
    let Some(markdown) = args.next() else {
        bail!("changelog pages requires Markdown and dates JSON files");
    };
    let Some(dates) = args.next() else {
        bail!("changelog pages requires Markdown and dates JSON files");
    };
    let notes = args.next();
    if args.next().is_some() {
        bail!("changelog pages accepts Markdown, dates JSON and optional notes JSON files");
    }
    let releases = parse_changelog(&std::fs::read_to_string(repo.join(markdown))?);
    let dates = serde_json::from_str(&std::fs::read_to_string(repo.join(dates))?)?;
    let notes: BTreeMap<String, Notes> = match notes {
        Some(path) => serde_json::from_str(&std::fs::read_to_string(repo.join(path))?)?,
        None => BTreeMap::new(),
    };
    let latest = releases
        .iter()
        .find(|r| is_stable_published(r, &dates))
        .map(|r| r.version.clone());
    let series = group_into_series(releases);
    let mut pages = Vec::new();
    for (index, item) in series.iter().enumerate() {
        let default_notes = Notes::default();
        let markdown = render_page(
            item,
            notes.get(&item.minor).unwrap_or(&default_notes),
            &dates,
            index.checked_sub(1).map(|i| series[i].minor.as_str()),
            series.get(index + 1).map(|s| s.minor.as_str()),
            latest.as_deref(),
        )?;
        pages.push(serde_json::json!({"minor":item.minor,"markdown":markdown}));
    }
    println!("{}", serde_json::to_string_pretty(&pages)?);
    Ok(())
}
