// @generated by `cargo xtask themes vendor`; do not edit by hand.

pub(crate) const BUNDLED_THEME_ASSETS: &[(&str, &str)] = &[
    (
        "andromeeda",
        include_str!("../assets/themes/andromeeda.json"),
    ),
    ("aurora-x", include_str!("../assets/themes/aurora-x.json")),
    ("ayu-dark", include_str!("../assets/themes/ayu-dark.json")),
    ("ayu-light", include_str!("../assets/themes/ayu-light.json")),
    (
        "ayu-mirage",
        include_str!("../assets/themes/ayu-mirage.json"),
    ),
    (
        "catppuccin-frappe",
        include_str!("../assets/themes/catppuccin-frappe.json"),
    ),
    (
        "catppuccin-latte",
        include_str!("../assets/themes/catppuccin-latte.json"),
    ),
    (
        "catppuccin-macchiato",
        include_str!("../assets/themes/catppuccin-macchiato.json"),
    ),
    (
        "catppuccin-mocha",
        include_str!("../assets/themes/catppuccin-mocha.json"),
    ),
    ("dark-plus", include_str!("../assets/themes/dark-plus.json")),
    ("dracula", include_str!("../assets/themes/dracula.json")),
    (
        "dracula-soft",
        include_str!("../assets/themes/dracula-soft.json"),
    ),
    (
        "everforest-dark",
        include_str!("../assets/themes/everforest-dark.json"),
    ),
    (
        "everforest-light",
        include_str!("../assets/themes/everforest-light.json"),
    ),
    (
        "github-dark",
        include_str!("../assets/themes/github-dark.json"),
    ),
    (
        "github-dark-default",
        include_str!("../assets/themes/github-dark-default.json"),
    ),
    (
        "github-dark-dimmed",
        include_str!("../assets/themes/github-dark-dimmed.json"),
    ),
    (
        "github-dark-high-contrast",
        include_str!("../assets/themes/github-dark-high-contrast.json"),
    ),
    (
        "github-light",
        include_str!("../assets/themes/github-light.json"),
    ),
    (
        "github-light-default",
        include_str!("../assets/themes/github-light-default.json"),
    ),
    (
        "github-light-high-contrast",
        include_str!("../assets/themes/github-light-high-contrast.json"),
    ),
    (
        "gruvbox-dark-hard",
        include_str!("../assets/themes/gruvbox-dark-hard.json"),
    ),
    (
        "gruvbox-dark-medium",
        include_str!("../assets/themes/gruvbox-dark-medium.json"),
    ),
    (
        "gruvbox-dark-soft",
        include_str!("../assets/themes/gruvbox-dark-soft.json"),
    ),
    (
        "gruvbox-light-hard",
        include_str!("../assets/themes/gruvbox-light-hard.json"),
    ),
    (
        "gruvbox-light-medium",
        include_str!("../assets/themes/gruvbox-light-medium.json"),
    ),
    (
        "gruvbox-light-soft",
        include_str!("../assets/themes/gruvbox-light-soft.json"),
    ),
    ("horizon", include_str!("../assets/themes/horizon.json")),
    (
        "horizon-bright",
        include_str!("../assets/themes/horizon-bright.json"),
    ),
    ("houston", include_str!("../assets/themes/houston.json")),
    (
        "kanagawa-dragon",
        include_str!("../assets/themes/kanagawa-dragon.json"),
    ),
    (
        "kanagawa-lotus",
        include_str!("../assets/themes/kanagawa-lotus.json"),
    ),
    (
        "kanagawa-wave",
        include_str!("../assets/themes/kanagawa-wave.json"),
    ),
    ("laserwave", include_str!("../assets/themes/laserwave.json")),
    (
        "light-plus",
        include_str!("../assets/themes/light-plus.json"),
    ),
    (
        "material-theme",
        include_str!("../assets/themes/material-theme.json"),
    ),
    (
        "material-theme-darker",
        include_str!("../assets/themes/material-theme-darker.json"),
    ),
    (
        "material-theme-lighter",
        include_str!("../assets/themes/material-theme-lighter.json"),
    ),
    (
        "material-theme-ocean",
        include_str!("../assets/themes/material-theme-ocean.json"),
    ),
    (
        "material-theme-palenight",
        include_str!("../assets/themes/material-theme-palenight.json"),
    ),
    ("min-dark", include_str!("../assets/themes/min-dark.json")),
    ("min-light", include_str!("../assets/themes/min-light.json")),
    ("monokai", include_str!("../assets/themes/monokai.json")),
    ("night-owl", include_str!("../assets/themes/night-owl.json")),
    (
        "night-owl-light",
        include_str!("../assets/themes/night-owl-light.json"),
    ),
    ("nord", include_str!("../assets/themes/nord.json")),
    (
        "one-dark-pro",
        include_str!("../assets/themes/one-dark-pro.json"),
    ),
    ("one-light", include_str!("../assets/themes/one-light.json")),
    (
        "pierre-dark",
        include_str!("../assets/themes/pierre-dark.json"),
    ),
    (
        "pierre-light",
        include_str!("../assets/themes/pierre-light.json"),
    ),
    ("plastic", include_str!("../assets/themes/plastic.json")),
    (
        "poimandres",
        include_str!("../assets/themes/poimandres.json"),
    ),
    ("red", include_str!("../assets/themes/red.json")),
    ("rose-pine", include_str!("../assets/themes/rose-pine.json")),
    (
        "rose-pine-dawn",
        include_str!("../assets/themes/rose-pine-dawn.json"),
    ),
    (
        "rose-pine-moon",
        include_str!("../assets/themes/rose-pine-moon.json"),
    ),
    (
        "slack-dark",
        include_str!("../assets/themes/slack-dark.json"),
    ),
    (
        "slack-ochin",
        include_str!("../assets/themes/slack-ochin.json"),
    ),
    (
        "snazzy-light",
        include_str!("../assets/themes/snazzy-light.json"),
    ),
    (
        "solarized-dark",
        include_str!("../assets/themes/solarized-dark.json"),
    ),
    (
        "solarized-light",
        include_str!("../assets/themes/solarized-light.json"),
    ),
    (
        "synthwave-84",
        include_str!("../assets/themes/synthwave-84.json"),
    ),
    (
        "tokyo-night",
        include_str!("../assets/themes/tokyo-night.json"),
    ),
    ("vesper", include_str!("../assets/themes/vesper.json")),
    (
        "vitesse-black",
        include_str!("../assets/themes/vitesse-black.json"),
    ),
    (
        "vitesse-dark",
        include_str!("../assets/themes/vitesse-dark.json"),
    ),
    (
        "vitesse-light",
        include_str!("../assets/themes/vitesse-light.json"),
    ),
];
