[package]
name = "workdeck-artifacts"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
mime_guess.workspace = true
percent-encoding.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tiny_http.workspace = true
unicode-normalization.workspace = true
workdeck-domain = { path = "../workdeck-domain" }
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
