[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.19"
flate2 = "1.1"
rnix = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
syn = { version = "2.0", features = ["full", "parsing"] }
tar = "0.4"
tempfile = "3.13"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
