//! Rust generation and verification of migrated MIT-licensed upstream release fragments.

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::Command;

const DATA: &str = "port/hunk/release-fragments.json";
const DOCUMENT: &str = "docs/upstream-release-fragments.md";
const BASELINE: &str = "2c00f4358b89cfc0a6b04459ffc538ba601aa3c2";

mod fragments;
mod website;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Archive {
    baseline: String,
    license: String,
    source_package: String,
    fragments: Vec<Fragment>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Fragment {
    path: String,
    blob: String,
    bump: Option<Bump>,
    body: String,
}

#[derive(Debug, Deserialize, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum Bump {
    Patch,
    Minor,
    Major,
}

impl Bump {
    fn as_str(self) -> &'static str {
        match self {
            Self::Patch => "patch",
            Self::Minor => "minor",
            Self::Major => "major",
        }
    }
}

impl Fragment {
    fn source_bytes(&self, package: &str) -> Vec<u8> {
        let mut source = String::from("---\n");
        if let Some(bump) = self.bump {
            writeln!(source, "\"{package}\": {}", bump.as_str()).unwrap();
        }
        source.push_str("---\n");
        if !self.body.is_empty() {
            source.push('\n');
            source.push_str(&self.body);
        }
        source.into_bytes()
    }
}

fn load(repo: &Path) -> Result<Archive> {
    let archive: Archive = serde_json::from_slice(&fs::read(repo.join(DATA))?)?;
    if archive.baseline != BASELINE || archive.source_package != "hunkdiff" {
        bail!("release archive does not identify the pinned source package and baseline");
    }
    if archive.license != "MIT; Copyright (c) Modem Labs Inc." {
        bail!("release archive must retain the source copyright and license");
    }
    if archive.fragments.len() != 77 {
        bail!("release archive must contain exactly 77 pinned Markdown fragments");
    }
    let mut previous = None;
    for fragment in &archive.fragments {
        if !fragment.path.starts_with(".changeset/")
            || !fragment.path.ends_with(".md")
            || fragment.path == ".changeset/README.md"
            || fragment.path.contains("..")
            || previous.is_some_and(|path: &str| path >= fragment.path.as_str())
        {
            bail!(
                "invalid, duplicate, or unsorted fragment path: {}",
                fragment.path
            );
        }
        if fragment.blob.len() != 40 || !fragment.blob.bytes().all(|b| b.is_ascii_hexdigit()) {
            bail!("invalid source blob for {}", fragment.path);
        }
        if !fragment.body.is_empty() && !fragment.body.ends_with('\n') {
            bail!(
                "fragment body must preserve its final newline: {}",
                fragment.path
            );
        }
        previous = Some(&fragment.path);
    }
    Ok(archive)
}

fn render(archive: &Archive) -> String {
    let mut output = format!(
        "# Pinned upstream release-fragment history\n\n\
         This is migrated historical documentation from Hunk commit `{}`.\n\
         It is **not** Workdeck release notes, a feature-completion claim, or current installation\n\
         guidance. Quoted upstream names, API generations, package managers, and runtime requirements\n\
         describe the source project at that pin; Workdeck ships a native Rust executable.\n\n\
         All 77 source fragments are represented, including 43 maintenance-only entries. The original\n\
         package target is `{}`. Bump metadata is historical and does not change Workdeck's version.\n\n\
         {}; the full permission notice is in [the third-party notices](../THIRD_PARTY_NOTICES).\n\n\
         Generated by `cargo xtask changelog upstream-history` from\n\
         [the migrated fragment data](../port/hunk/release-fragments.json).\n\
         Check exact source reconstruction and this document with\n\
         `cargo xtask changelog upstream-history --check`. No source runtime is needed.\n\n",
        archive.baseline, archive.source_package, archive.license
    );
    for fragment in &archive.fragments {
        writeln!(
            output,
            "## {}\n",
            fragment.path.strip_prefix(".changeset/").unwrap()
        )
        .unwrap();
        writeln!(output, "Source blob: `{}`.\n", fragment.blob).unwrap();
        let bump = fragment
            .bump
            .map(Bump::as_str)
            .unwrap_or("none (maintenance only)");
        writeln!(output, "Requested version bump: {bump}.\n").unwrap();
        if fragment.body.is_empty() {
            output.push_str("No release-note body was present in this source fragment.\n\n");
        } else {
            for line in fragment.body.strip_suffix('\n').unwrap().split('\n') {
                writeln!(output, "> {line}").unwrap();
            }
            output.push('\n');
        }
    }
    output
}

fn git(repo: &Path, args: &[&str]) -> Result<Vec<u8>> {
    let output = Command::new("git").args(args).current_dir(repo).output()?;
    if !output.status.success() {
        bail!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(output.stdout)
}

fn verify_sources(repo: &Path, archive: &Archive) -> Result<()> {
    let tree = git(
        repo,
        &["ls-tree", "-r", "--name-only", BASELINE, ".changeset"],
    )?;
    let expected = std::str::from_utf8(&tree)?
        .lines()
        .filter(|path| path.ends_with(".md") && *path != ".changeset/README.md")
        .collect::<BTreeSet<_>>();
    let actual = archive
        .fragments
        .iter()
        .map(|fragment| fragment.path.as_str())
        .collect::<BTreeSet<_>>();
    if expected != actual {
        bail!("migrated release fragments do not cover the exact pinned fragment paths");
    }
    for fragment in &archive.fragments {
        let reference = format!("{BASELINE}:{}", fragment.path);
        let blob = git(repo, &["rev-parse", &reference])?;
        if std::str::from_utf8(&blob)?.trim() != fragment.blob {
            bail!("source blob mismatch for {}", fragment.path);
        }
        let source = git(repo, &["show", &reference])?;
        if source != fragment.source_bytes(&archive.source_package) {
            bail!(
                "migrated fragment loses or changes source bytes: {}",
                fragment.path
            );
        }
    }
    Ok(())
}

pub(super) fn run(repo: &Path, mut args: impl Iterator<Item = String>) -> Result<()> {
    match args.next().as_deref() {
        Some("add") => return fragments::add(repo, args),
        Some("status") => return fragments::status(repo, args),
        Some("plan") => return fragments::plan(repo, args),
        Some("check-plan") => return fragments::check_plan(repo, args),
        Some("apply-plan") => return fragments::apply_plan(repo, args),
        Some("parse") => return website::run(repo, args, false),
        Some("series") => return website::run(repo, args, true),
        Some("dates") => return website::run_dates(repo, args),
        Some("summaries") => return website::run_summaries(repo, args, false),
        Some("resolved-summaries") => return website::run_summaries(repo, args, true),
        Some("publication") => return website::run_publication(repo, args),
        Some("release-notes") => return website::run_release_notes(repo, args),
        Some("metadata") => return website::run_metadata(repo, args),
        Some("video") => return website::run_video(repo, args),
        Some("pages") => return website::run_pages(repo, args),
        Some("index-card") => return website::run_index_card(repo, args),
        Some("feed") => return website::run_feed(repo, args),
        Some("index") => return website::run_index(repo, args),
        Some("latest") => return website::run_latest(repo, args),
        Some("artifacts") => return website::run_artifacts(repo, args, "generate"),
        Some("artifacts-check") => return website::run_artifacts(repo, args, "check"),
        Some("artifacts-plan") => return website::run_artifacts(repo, args, "plan"),
        Some("artifacts-plan-check") => return website::run_artifacts(repo, args, "plan-check"),
        Some("upstream-history") => {}
        _ => bail!(
            "changelog requires parse <markdown-file>, series <markdown-file>, summaries <markdown-file> [notes.json], resolved-summaries <markdown-file> <dates.json> [notes.json], dates <markdown-file> <recorded-dates.json>, publication <markdown-file> <dates.json>, release-notes <markdown-file> <dates.json>, metadata <markdown-file> <dates.json>, video <input.json>, pages <markdown-file> <dates.json> [notes.json], index-card <markdown-file> <dates.json>, feed <markdown-file> <dates.json> [notes.json], index <markdown-file> <dates.json> [notes.json], latest <markdown-file> <recorded-dates.json> [notes.json], upstream-history [--check], add <id> <patch|minor|major|empty> [body], status, plan, check-plan <saved-plan.json>, or apply-plan <saved-plan.json> <new-backup-directory>"
        ),
    }
    let check = match args.next().as_deref() {
        Some("--check") => true,
        None => false,
        Some(other) => bail!("unknown changelog option {other}"),
    };
    if args.next().is_some() {
        bail!("changelog upstream-history accepts only --check");
    }
    let archive = load(repo)?;
    verify_sources(repo, &archive)?;
    let document = render(&archive);
    if check {
        let actual =
            fs::read_to_string(repo.join(DOCUMENT)).context("missing generated release history")?;
        if actual != document {
            bail!("{DOCUMENT} is stale; regenerate the upstream history");
        }
        println!("verified all 77 release fragments, exact source bytes, and generated history");
    } else {
        print!("{document}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_pinned_release_fragment_is_losslessly_migrated_and_rendered() {
        let repo = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let archive = load(repo).unwrap();
        verify_sources(repo, &archive).unwrap();
        assert_eq!(
            archive
                .fragments
                .iter()
                .filter(|fragment| fragment.bump.is_none())
                .count(),
            43
        );
        let document = render(&archive);
        assert_eq!(document, fs::read_to_string(repo.join(DOCUMENT)).unwrap());
        assert_eq!(document.matches("\n## ").count(), 77);
        for fragment in &archive.fragments {
            assert!(document.contains(&fragment.blob));
            for line in fragment.body.lines() {
                assert!(document.contains(&format!("> {line}\n")));
            }
        }
    }

    #[test]
    fn fragment_reconstruction_keeps_maintenance_body_and_bump_frontmatter_separate() {
        let mut fragment = Fragment {
            path: String::new(),
            blob: String::new(),
            bump: None,
            body: String::new(),
        };
        assert_eq!(fragment.source_bytes("workdeck"), b"---\n---\n");
        fragment.body = "Maintenance detail.\n".into();
        assert_eq!(
            fragment.source_bytes("workdeck"),
            b"---\n---\n\nMaintenance detail.\n"
        );
        for (bump, name) in [
            (Bump::Patch, "patch"),
            (Bump::Minor, "minor"),
            (Bump::Major, "major"),
        ] {
            fragment.bump = Some(bump);
            assert_eq!(
                fragment.source_bytes("workdeck"),
                format!("---\n\"workdeck\": {name}\n---\n\nMaintenance detail.\n").as_bytes()
            );
        }
    }

    #[test]
    fn source_verification_rejects_changed_text_metadata_and_missing_fragments() {
        let repo = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let mut archive = load(repo).unwrap();
        archive.fragments[0].body = "An invented release note.\n".into();
        assert!(
            verify_sources(repo, &archive)
                .unwrap_err()
                .to_string()
                .contains("source bytes")
        );

        let mut archive = load(repo).unwrap();
        archive.fragments[0].bump = Some(Bump::Major);
        assert!(
            verify_sources(repo, &archive)
                .unwrap_err()
                .to_string()
                .contains("source bytes")
        );

        let mut archive = load(repo).unwrap();
        archive.fragments[0].blob = "0".repeat(40);
        assert!(
            verify_sources(repo, &archive)
                .unwrap_err()
                .to_string()
                .contains("blob mismatch")
        );

        let mut archive = load(repo).unwrap();
        archive.fragments.remove(0);
        assert!(
            verify_sources(repo, &archive)
                .unwrap_err()
                .to_string()
                .contains("exact pinned fragment paths")
        );
    }
}
