//! Deterministic native documentation generation.
//!
//! Hunk generated its CLI and configuration references from runtime metadata.
//! Workdeck keeps that same invariant: the Rust catalogs used by the CLI and
//! session daemon render the checked-in reference pages, while this module
//! provides a no-runtime-mirror stale-output gate.

use anyhow::{Context, Result, bail};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};
use workdeck_cli::config::{
    CONFIG_COMMAND_SECTIONS, CONFIG_REFERENCE_CUSTOM_THEME, CONFIG_REFERENCE_EXTENSIONS,
    CONFIG_REFERENCE_OPTIONS, ConfigReferenceDefault,
};
use workdeck_core::{BUNDLED_SHIKI_THEME_IDS, LEGACY_THEME_ID_ALIASES};
use workdeck_session::SESSION_AGENT_COMMAND_LIST;

const CLI_PAGE: &str = "site/content/docs/reference/cli.md";
const CONFIG_PAGE: &str = "site/content/docs/reference/config.md";
const GENERATED_NOTICE: &str = "<!-- GENERATED by `cargo xtask docs generate`. Edit the Rust command/config catalogs instead. -->";

const GLOBAL_OPTIONS: &[(&str, &str)] = &[
    ("-h, --help", "Show top-level or command-specific help."),
    ("-V, --version", "Print the installed Workdeck version."),
    (
        "--cwd <path>",
        "Resolve repository and local state from this path (default: `.`).",
    ),
    (
        "--extension <path>",
        "Load a native extension manifest or directory (repeatable).",
    ),
    ("--no-extensions", "Disable user extensions for this run."),
    (
        "--experimental",
        "Enable experimental review features such as STML.",
    ),
    ("--fast", "Use experimental fast syntax highlighting."),
];

const REVIEW_OPTIONS: &[(&str, &str)] = &[
    (
        "--mode <auto|split|stack>",
        "Select responsive, side-by-side, or stacked review layout.",
    ),
    (
        "--watch",
        "Reload supported review inputs when their source changes.",
    ),
    (
        "--agent-context <path>",
        "Load a JSON sidecar with agent rationale.",
    ),
    ("--pager", "Use pager-style review chrome."),
    (
        "--line-numbers / --no-line-numbers",
        "Show or hide old and new line numbers.",
    ),
    (
        "-x, --tab-width <columns>",
        "Set terminal tab stops from 1 through 16 (default: 4).",
    ),
    (
        "--file-gap <rows>",
        "Set file separator rows from 0 through 8 (default: 1).",
    ),
    (
        "--hunk-gap <rows>",
        "Set blank rows before later hunks from 0 through 8 (default: 0).",
    ),
    ("--wrap / --no-wrap", "Wrap or truncate long diff lines."),
    (
        "--hunk-headers / --no-hunk-headers",
        "Show or hide hunk metadata rows.",
    ),
    ("--sidebar / --no-sidebar", "Show or hide the files pane."),
    (
        "--agent-notes / --no-agent-notes",
        "Show or hide agent notes.",
    ),
    (
        "--transparent-bg / --no-transparent-bg",
        "Use transparent or themed surfaces.",
    ),
    (
        "--theme <theme>",
        "Select a bundled, extension, or custom theme.",
    ),
];

const REVIEW_COMMANDS: &[(&str, &str, &[&str])] = &[
    (
        "diff",
        "Review working-tree, staged, revision-range, or concrete-file changes.",
        &[
            "workdeck diff [REVISION] [-- <pathspec...>]",
            "workdeck diff <FROM> <TO> [-- <pathspec...>]",
            "workdeck diff --staged [-- <pathspec...>]",
            "workdeck diff --files <LEFT> <RIGHT>",
        ],
    ),
    (
        "show",
        "Review the last commit or a given revision.",
        &["workdeck show [TARGET] [-- <pathspec...>]"],
    ),
    (
        "stash show",
        "Review a Git stash entry as a complete changeset.",
        &["workdeck stash show [REF]"],
    ),
    (
        "patch",
        "Review a patch file or read a unified patch from stdin.",
        &["workdeck patch [FILE]"],
    ),
    (
        "pager",
        "Wrap a Git pager invocation and detect its diff input.",
        &["workdeck pager"],
    ),
    (
        "difftool",
        "Review a Git difftool file pair.",
        &["workdeck difftool <LEFT> <RIGHT> [PATH]"],
    ),
];

const UTILITY_COMMANDS: &[(&str, &str, &str)] = &[
    (
        "status",
        "Print a Git status snapshot.",
        "workdeck status [--json]",
    ),
    (
        "files",
        "Inspect repository files without opening the TUI.",
        "workdeck files <list|show|preview> ...",
    ),
    (
        "changes",
        "Inspect headless changes and preserve JSON/JSONL output.",
        "workdeck changes diff [OPTIONS]",
    ),
    (
        "search",
        "Search files, changes, issues, and agent data.",
        "workdeck search <QUERY> [--target ...] [--json]",
    ),
    (
        "config",
        "Inspect and update Workdeck configuration.",
        "workdeck config <show|path|set|reset> ...",
    ),
    (
        "events",
        "Inspect the append-only Workdeck event log.",
        "workdeck events <list|export> ...",
    ),
    (
        "import",
        "Validate or import Workdeck JSON data.",
        "workdeck import <PATH> [--dry-run|--merge|--replace]",
    ),
    (
        "export",
        "Export Workdeck data as JSON or JSONL.",
        "workdeck export [--json|--jsonl]",
    ),
    (
        "doctor",
        "Validate repository, configuration, and local Workdeck data.",
        "workdeck doctor [--json]",
    ),
    (
        "issue",
        "Manage local Workdeck issues.",
        "workdeck issue <list|show|add|edit|close> ...",
    ),
    (
        "agent",
        "Manage local agent sessions.",
        "workdeck agent <list|show|add|edit|remove> ...",
    ),
    (
        "project",
        "Manage local Workdeck projects.",
        "workdeck project <list|show|add|edit|archive> ...",
    ),
    (
        "cycle",
        "Manage local Workdeck cycles.",
        "workdeck cycle <list|show|add|edit|close> ...",
    ),
    (
        "label",
        "Manage local Workdeck labels.",
        "workdeck label <list|add|edit|remove> ...",
    ),
    (
        "migrate",
        "Migrate legacy review-tool data without dual-reading after success.",
        "workdeck migrate hunk [--dry-run|--apply]",
    ),
    (
        "markup",
        "Render or inspect terminal-safe Workdeck markup.",
        "workdeck markup <render|check> ...",
    ),
    (
        "skill",
        "Print or materialize a bundled Workdeck agent skill.",
        "workdeck skill path [NAME]",
    ),
    (
        "extension",
        "Manage native Workdeck extensions.",
        "workdeck extension <list|install|update|remove> ...",
    ),
    (
        "update",
        "Update Workdeck through the detected installation channel.",
        "workdeck update [VERSION] [--method ...] [--check]",
    ),
];

fn table(rows: impl IntoIterator<Item = (String, String)>) -> String {
    let rows = rows.into_iter().collect::<Vec<_>>();
    if rows.is_empty() {
        return "No entries.".into();
    }
    let mut output = String::from("| Option | Description |\n| --- | --- |\n");
    for (key, value) in rows {
        output.push_str(&format!(
            "| `{}` | {} |\n",
            key.replace('|', "\\|"),
            value.replace('|', "\\|")
        ));
    }
    output
}

fn default_value(value: Option<ConfigReferenceDefault>) -> String {
    match value {
        Some(ConfigReferenceDefault::String(value)) => format!("`{value}`"),
        Some(ConfigReferenceDefault::Integer(value)) => format!("`{value}`"),
        Some(ConfigReferenceDefault::Boolean(value)) => format!("`{value}`"),
        None => "—".into(),
    }
}

fn render_session_command(spec: &workdeck_session::AgentCommandSpec) -> String {
    let mut output = format!("### `{}`\n\n{}\n\n", spec.name, spec.summary);
    output.push_str("```text\n");
    for synopsis in &spec.synopsis {
        output.push_str(synopsis);
        output.push('\n');
    }
    output.push_str("```\n\n");
    if !spec.options.is_empty() {
        output.push_str(&table(spec.options.iter().map(|option| {
            let required = if option.required { " Required." } else { "" };
            (
                option.flag.to_owned(),
                format!("{}{}", option.description, required),
            )
        })));
        output.push('\n');
    }
    if !spec.positionals.is_empty() {
        output.push_str("Positionals: ");
        output.push_str(
            &spec
                .positionals
                .iter()
                .map(|positional| {
                    positional.description.map_or_else(
                        || format!("`{}`", positional.token),
                        |description| format!("`{}` — {}", positional.token, description),
                    )
                })
                .collect::<Vec<_>>()
                .join("; "),
        );
        output.push_str(".\n\n");
    }
    if !spec.examples.is_empty() {
        output.push_str("Examples:\n\n```text\n");
        for example in &spec.examples {
            output.push_str(example);
            output.push('\n');
        }
        output.push_str("```\n\n");
    }
    output
}

pub(crate) fn render_cli_reference() -> String {
    let mut output = format!(
        "+++\ntitle = \"CLI reference\"\ndescription = \"Exhaustive generated reference for Workdeck commands, options, and live-session controls.\"\ntemplate = \"docs.html\"\n+++\n\n{GENERATED_NOTICE}\n\n"
    );
    output.push_str("This reference is generated from the Rust command and session catalogs used by Workdeck itself. Run `workdeck --help` or `workdeck <command> --help` for the installed version.\n\n## Global options\n\n");
    output.push_str(&table(
        GLOBAL_OPTIONS
            .iter()
            .map(|(key, value)| ((*key).into(), (*value).into())),
    ));
    output.push_str("\n## Common review options\n\n");
    output.push_str(&table(
        REVIEW_OPTIONS
            .iter()
            .map(|(key, value)| ((*key).into(), (*value).into())),
    ));
    for (name, summary, usage) in REVIEW_COMMANDS {
        output.push_str(&format!("\n## `workdeck {name}`\n\n{summary}\n\n### Usage\n\n```bash\n{}\n```\n\nAlso accepts the common review options and `--watch`.\n", usage.join("\n")));
    }
    output.push_str("\n## Live sessions\n\nThe loopback session broker exposes review, context, navigation, reload, comment, highlight, and quit controls without taking ownership of the interactive TUI.\n\n");
    for spec in SESSION_AGENT_COMMAND_LIST.iter() {
        output.push_str(&render_session_command(spec));
    }
    output.push_str("\n## Workdeck capabilities\n\n");
    for (name, summary, usage) in UTILITY_COMMANDS {
        output.push_str(&format!(
            "### `workdeck {name}`\n\n{summary}\n\n```text\n{usage}\n```\n\n"
        ));
    }
    output
}

pub(crate) fn render_config_reference() -> String {
    let mut output = format!(
        "+++\ntitle = \"Config reference\"\ndescription = \"Exhaustive generated reference for Workdeck TOML keys, defaults, aliases, and layering.\"\ntemplate = \"docs.html\"\n+++\n\n{GENERATED_NOTICE}\n\n"
    );
    output.push_str("Workdeck reads TOML preferences from the user config and an optional repository config. The same typed catalog drives runtime parsing and this page.\n\n## Resolution and scope\n\nLayers apply from lowest to highest precedence:\n\n1. built-in defaults\n2. user config top-level keys, then the matching command table and `[pager]` overlay\n3. repository `.agents/workdeck/config.toml` keys and overlays\n4. explicit CLI options\n\nThe user path is `~/.config/workdeck/config.toml`; repository state remains under `.agents/workdeck/`.\n\n## Preference keys\n\n");
    for option in CONFIG_REFERENCE_OPTIONS {
        output.push_str(&format!(
            "**`{}`**\n\n{}\n\n- **Type:** {}\n- **Accepted:** {}\n- **Built-in default:** {}\n",
            option.key,
            option.description,
            option.value_type,
            option.accepted,
            default_value(option.runtime_default)
        ));
        for alias in option.aliases {
            output.push_str(&format!(
                "- **Alias:** `{}`{}\n",
                alias.key,
                if alias.deprecated {
                    " (deprecated)"
                } else {
                    ""
                }
            ));
        }
        output.push_str("\n---\n\n");
    }
    output.push_str("## Command tables\n\n");
    output.push_str(&table(CONFIG_COMMAND_SECTIONS.iter().map(
        |(name, description)| (format!("[{name}]"), (*description).into()),
    )));
    output.push_str("\n`[pager]` overlays the matching review command for pager-style chrome.\n\n## Custom themes\n\nSet `theme = \"custom\"` and define a root `[custom_theme]` table. Built-in bases include:\n\n");
    for id in BUNDLED_SHIKI_THEME_IDS {
        output.push_str(&format!("- `{id}`\n"));
    }
    output.push_str("\nLegacy theme ids are accepted and normalized:\n\n");
    output.push_str(&table(LEGACY_THEME_ID_ALIASES.iter().map(
        |(alias, replacement)| (alias.to_string(), format!("`{replacement}`")),
    )));
    output.push_str(&format!("\n`[{}]` accepts a label, base, and semantic six-digit colors. Syntax overrides live in `[{}]`.\n\n", CONFIG_REFERENCE_CUSTOM_THEME.table, CONFIG_REFERENCE_CUSTOM_THEME.syntax_scopes_table));
    output.push_str("## Extensions\n\n");
    output.push_str(&table(CONFIG_REFERENCE_EXTENSIONS.keys.iter().map(|key| {
        (
            key.key.into(),
            format!(
                "{}; accepted: {}; default: {}. {}",
                key.value_type,
                key.accepted,
                key.default_value.unwrap_or("—"),
                key.description
            ),
        )
    })));
    output.push_str("\nRepository extension paths are trust-gated native executables. User extension settings are passed through from `[extension.<id>]` tables.\n");
    output
}

pub(crate) fn artifacts(repo: &Path) -> BTreeMap<PathBuf, String> {
    BTreeMap::from([
        (repo.join(CLI_PAGE), render_cli_reference()),
        (repo.join(CONFIG_PAGE), render_config_reference()),
    ])
}

pub(crate) fn generate(repo: &Path) -> Result<()> {
    for (path, content) in artifacts(repo) {
        fs::create_dir_all(path.parent().context("generated docs parent")?)?;
        if fs::read_to_string(&path).ok().as_deref() != Some(content.as_str()) {
            fs::write(&path, content).with_context(|| format!("write {}", path.display()))?;
            println!(
                "wrote {}",
                path.strip_prefix(repo).unwrap_or(&path).display()
            );
        }
    }
    Ok(())
}

pub(crate) fn check(repo: &Path) -> Result<()> {
    let mut stale = Vec::new();
    for (path, content) in artifacts(repo) {
        match fs::read_to_string(&path) {
            Ok(current) if current == content => {}
            Ok(_) | Err(_) => stale.push(path),
        }
    }
    if let Some(path) = stale.first() {
        bail!(
            "generated documentation is stale: {}; run `cargo xtask docs generate`",
            path.display()
        );
    }
    println!("Workdeck generated reference pages are current");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use workdeck_session::agent_option_flag_name;

    #[test]
    fn cli_reference_is_native_and_exhaustive_for_review_and_sessions() {
        let page = render_cli_reference();
        assert!(page.contains("workdeck diff --files <LEFT> <RIGHT>"));
        assert!(page.contains("workdeck changes diff"));
        assert!(!page.contains("hunk diff") && !page.contains("bun run"));
        for spec in SESSION_AGENT_COMMAND_LIST.iter() {
            assert!(page.contains(&format!("### `{}`", spec.name)));
            for option in &spec.options {
                assert!(
                    page.contains(agent_option_flag_name(option)),
                    "{}",
                    spec.name
                );
            }
        }
    }

    #[test]
    fn config_reference_comes_from_the_runtime_catalog() {
        let page = render_config_reference();
        for option in CONFIG_REFERENCE_OPTIONS {
            assert!(page.contains(&format!("`{}`", option.key)));
        }
        assert!(page.contains("`.agents/workdeck/config.toml`"));
        assert!(page.contains("[custom_theme.syntax_scopes]"));
        assert!(page.contains("`extensions.enabled`"));
    }

    #[test]
    fn stale_check_is_read_only_and_generation_repairs_output() {
        let repo = tempfile::tempdir().unwrap();
        fs::create_dir_all(repo.path().join("site/content/docs/reference")).unwrap();
        fs::write(repo.path().join(CLI_PAGE), "stale\n").unwrap();
        assert!(check(repo.path()).is_err());
        generate(repo.path()).unwrap();
        check(repo.path()).unwrap();
        assert_eq!(
            fs::read_to_string(repo.path().join(CLI_PAGE)).unwrap(),
            render_cli_reference()
        );
    }

    #[test]
    fn deployment_page_keeps_the_native_static_pipeline_contract() {
        let repo = crate::repo_root().unwrap();
        let page = fs::read_to_string(repo.join("site/content/docs/help/deployment.md")).unwrap();
        for required in [
            "cargo xtask site check",
            "cargo xtask site build",
            "site/public",
            "https://workdeck.dev/sitemap.xml",
        ] {
            assert!(page.contains(required), "missing {required}");
        }
        assert!(!page.contains("bun run") && !page.contains("npm install"));
    }
}
