//! Reproduce licensed upstream contribution forms and dependency-update policy.
use anyhow::{Context, Result, ensure};
use std::{fs, path::Path};

const BASELINE: &str = "2c00f4358b89cfc0a6b04459ffc538ba601aa3c2";
const FILES: [&str; 5] = [
    "CONTRIBUTING.md",
    ".github/ISSUE_TEMPLATE/bug.yml",
    ".github/ISSUE_TEMPLATE/contribution.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/dependabot.yml",
];
const NOTICE: &str = "# Adapted from Hunk 2c00f435, copyright Modem Labs Inc., MIT.\n# See THIRD_PARTY_NOTICES. Generated by cargo xtask repository-forms generate.\n";

fn adapt(source: &str) -> Result<String> {
    ensure!(
        source
            .matches("https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md")
            .count()
            == 1,
        "upstream contribution link changed"
    );
    let adapted = source
        .replace(
            "https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md",
            "https://github.com/ruttydm/workdeck/blob/main/CONTRIBUTING.md",
        )
        .replace(
            "What did you expect Hunk to do instead?",
            "What did you expect Workdeck to do instead?",
        )
        .replace(
            "e.g. output from `hunk --version` or the npm package version",
            "e.g. output from `workdeck --version` and the installation method",
        );
    // Parsing complements exact-byte comparison: malformed source or transforms
    // cannot silently produce unusable GitHub form YAML.
    let form: serde_norway::Value = serde_norway::from_str(&adapted)?;
    ensure!(
        form["body"]
            .as_sequence()
            .is_some_and(|body| !body.is_empty()),
        "issue form has no fields"
    );
    Ok(format!("{NOTICE}{adapted}"))
}

fn adapt_issue_config(source: &str) -> Result<String> {
    ensure!(
        source.matches("https://discord.gg/WZFjaP6Gt8").count() == 1,
        "upstream issue contact link changed"
    );
    let adapted = source
        .replace(
            "https://discord.gg/WZFjaP6Gt8",
            "https://github.com/ruttydm/workdeck/issues",
        )
        .replace(
            "Ask questions or discuss ideas on Discord instead of opening an issue",
            "Ask questions or discuss ideas in Workdeck issues instead of opening a new issue",
        );
    let config: serde_norway::Value = serde_norway::from_str(&adapted)?;
    ensure!(
        config["blank_issues_enabled"].as_bool() == Some(false),
        "issue config must disable blank issues"
    );
    ensure!(
        config["contact_links"].as_sequence().is_some_and(|links| {
            links.len() == 1
                && links[0]["url"].as_str() == Some("https://github.com/ruttydm/workdeck/issues")
                && links[0]["about"]
                    .as_str()
                    .is_some_and(|about| about.contains("Workdeck issues"))
        }),
        "issue config contact link must target Workdeck issues"
    );
    Ok(format!("{NOTICE}{adapted}"))
}

fn retain_update_policy(source: &str) -> Result<String> {
    let parsed: serde_json::Value = serde_norway::from_str(source)?;
    ensure!(
        parsed
            == serde_json::json!({
                "version": 2,
                "updates": [{
                    "package-ecosystem": "github-actions",
                    "directory": "/",
                    "schedule": { "interval": "monthly" },
                    "cooldown": { "default-days": 14 },
                    "groups": { "github-actions": { "patterns": ["*"] } },
                    "open-pull-requests-limit": 1
                }]
            }),
        "pinned dependency-update policy changed"
    );
    Ok(format!("{NOTICE}{source}"))
}

pub(crate) fn run(repo: &Path, generate: bool) -> Result<()> {
    for relative in FILES {
        let source = String::from_utf8(crate::git_stdout_bytes(
            repo,
            ["show", &format!("{BASELINE}:{relative}")],
        )?)?;
        let expected = if relative == "CONTRIBUTING.md" {
            let guide = crate::contributor_guide::render(&source)?;
            crate::contributor_guide::check_links(repo, &guide)?;
            guide
        } else if relative == ".github/dependabot.yml" {
            retain_update_policy(&source)?
        } else if relative == ".github/ISSUE_TEMPLATE/config.yml" {
            adapt_issue_config(&source)?
        } else {
            adapt(&source)?
        };
        let destination = repo.join(relative);
        let mut checked = repo.to_owned();
        for component in Path::new(relative).components() {
            checked.push(component);
            match fs::symlink_metadata(&checked) {
                Ok(metadata) => ensure!(
                    !metadata.file_type().is_symlink(),
                    "repository policy path is a symlink"
                ),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                Err(error) => return Err(error.into()),
            }
        }
        if generate {
            fs::create_dir_all(destination.parent().context("form parent")?)?;
            fs::write(&destination, &expected)?;
        }
        ensure!(
            fs::read_to_string(&destination).with_context(|| format!("read {relative}"))?
                == expected,
            "{relative} is stale; run cargo xtask repository-forms generate"
        );
    }
    Ok(())
}

pub(crate) fn verify(repo: &Path, baseline: &str) -> Result<()> {
    if baseline == BASELINE {
        run(repo, false)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_artifacts_match_raw_blobs_including_final_newlines() {
        let repo = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        for (relative, expected_bytes) in FILES.into_iter().zip([8682, 1152, 978, 198, 256]) {
            let bytes =
                crate::git_stdout_bytes(repo, ["show", &format!("{BASELINE}:{relative}")]).unwrap();
            assert_eq!(bytes.len(), expected_bytes, "{relative}");
            assert!(bytes.ends_with(b"\n"), "source final newline: {relative}");
            let source = String::from_utf8(bytes).unwrap();
            let expected = match relative {
                "CONTRIBUTING.md" => crate::contributor_guide::render(&source).unwrap(),
                ".github/dependabot.yml" => retain_update_policy(&source).unwrap(),
                ".github/ISSUE_TEMPLATE/config.yml" => adapt_issue_config(&source).unwrap(),
                _ => adapt(&source).unwrap(),
            };
            let actual = fs::read(repo.join(relative)).unwrap();
            assert!(
                actual.ends_with(b"\n"),
                "generated final newline: {relative}"
            );
            assert_eq!(
                actual,
                expected.as_bytes(),
                "whole raw artifact: {relative}"
            );
        }
    }

    #[test]
    fn dependency_policy_preserves_all_bytes_and_rejects_semantic_drift() {
        let source = "version: 2\nupdates:\n  - package-ecosystem: \"github-actions\"\n    directory: \"/\"\n    schedule:\n      interval: \"monthly\"\n    cooldown:\n      default-days: 14\n    groups:\n      github-actions:\n        patterns:\n          - \"*\"\n    open-pull-requests-limit: 1\n";
        assert_eq!(
            retain_update_policy(source).unwrap(),
            format!("{NOTICE}{source}")
        );
        for (before, after) in [
            ("version: 2", "version: 1"),
            (
                "package-ecosystem: \"github-actions\"",
                "package-ecosystem: \"npm\"",
            ),
            ("directory: \"/\"", "directory: \"/other\""),
            ("monthly", "weekly"),
            ("default-days: 14", "default-days: 0"),
            ("- \"*\"", "- \"actions/*\""),
            ("open-pull-requests-limit: 1", "open-pull-requests-limit: 5"),
        ] {
            assert!(
                retain_update_policy(&source.replace(before, after)).is_err(),
                "{before}"
            );
        }
        assert!(retain_update_policy("version: [").is_err());
        assert!(retain_update_policy(&format!("{source}extra: true\n")).is_err());
    }

    #[test]
    fn adaptations_preserve_complete_form_structure_and_requirements() {
        let source = "name: Bug Report\nlabels: [bug]\nbody:\n  - type: markdown\n    attributes:\n      value: https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md\n  - type: textarea\n    id: expected\n    attributes:\n      description: What did you expect Hunk to do instead?\n    validations:\n      required: false\n  - type: input\n    id: version\n    attributes:\n      description: e.g. output from `hunk --version` or the npm package version\n    validations:\n      required: true\n";
        let expected = source
            .replace("modem-dev/hunk", "ruttydm/workdeck")
            .replace("expect Hunk", "expect Workdeck")
            .replace(
                "`hunk --version` or the npm package version",
                "`workdeck --version` and the installation method",
            );
        let actual = adapt(source).unwrap();
        assert_eq!(actual, format!("{NOTICE}{expected}"));
        let parsed: serde_norway::Value = serde_norway::from_str(&actual).unwrap();
        assert_eq!(
            parsed["body"][1]["validations"]["required"].as_bool(),
            Some(false)
        );
        assert_eq!(
            parsed["body"][2]["validations"]["required"].as_bool(),
            Some(true)
        );
    }

    #[test]
    fn absent_duplicate_links_and_malformed_forms_are_rejected() {
        assert!(adapt("body: []").is_err());
        let link = "https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md";
        assert!(adapt(&format!("body: []\n# {link}\n# {link}\n")).is_err());
        assert!(adapt(&format!("body: []\n# {link}\n")).is_err());
        assert!(adapt(&format!("body: [\n# {link}\n")).is_err());
    }

    #[test]
    fn issue_contact_config_moves_questions_to_the_native_discussion_path() {
        let source = "blank_issues_enabled: false\ncontact_links:\n - name: Questions and discussion\n   url: https://discord.gg/WZFjaP6Gt8\n   about: Ask questions or discuss ideas on Discord instead of opening an issue\n";
        let adapted = adapt_issue_config(source).unwrap();
        assert!(adapted.contains("https://github.com/ruttydm/workdeck/issues"));
        assert!(adapted.contains("in Workdeck issues instead of opening a new issue"));
        assert!(!adapted.contains("discord.gg"));
        assert!(adapt_issue_config("blank_issues_enabled: true\n").is_err());
        assert!(adapt_issue_config("contact_links: []\n").is_err());
        assert!(adapt_issue_config(&source.replace("WZFjaP6Gt8", "changed")).is_err());
    }
}
