//! Reproduce licensed upstream issue forms with explicit Workdeck adaptations.
use anyhow::{Context, Result, ensure};
use std::{fs, path::Path};

const BASELINE: &str = "2c00f4358b89cfc0a6b04459ffc538ba601aa3c2";
const FORMS: [&str; 2] = ["bug.yml", "contribution.yml"];
const NOTICE: &str = "# Adapted from Hunk 2c00f435, copyright Modem Labs Inc., MIT.\n# See THIRD_PARTY_NOTICES. Generated by cargo xtask repository-forms generate.\n";

fn adapt(source: &str) -> Result<String> {
    ensure!(
        source
            .matches("https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md")
            .count()
            == 1,
        "upstream contribution link changed"
    );
    let adapted = source
        .replace(
            "https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md",
            "https://github.com/ruttydm/workdeck/blob/main/CONTRIBUTING.md",
        )
        .replace(
            "What did you expect Hunk to do instead?",
            "What did you expect Workdeck to do instead?",
        )
        .replace(
            "e.g. output from `hunk --version` or the npm package version",
            "e.g. output from `workdeck --version` and the installation method",
        );
    // Parsing complements exact-byte comparison: malformed source or transforms
    // cannot silently produce unusable GitHub form YAML.
    let form: serde_norway::Value = serde_norway::from_str(&adapted)?;
    ensure!(
        form["body"]
            .as_sequence()
            .is_some_and(|body| !body.is_empty()),
        "issue form has no fields"
    );
    Ok(format!("{NOTICE}{adapted}"))
}

pub(crate) fn run(repo: &Path, generate: bool) -> Result<()> {
    ensure!(
        repo.join("CONTRIBUTING.md").is_file(),
        "contribution guide is missing"
    );
    for name in FORMS {
        let relative = format!(".github/ISSUE_TEMPLATE/{name}");
        let source = crate::git_stdout(repo, ["show", &format!("{BASELINE}:{relative}")])?;
        let expected = adapt(&source)?;
        let destination = repo.join(&relative);
        let mut checked = repo.to_owned();
        for component in Path::new(&relative).components() {
            checked.push(component);
            match fs::symlink_metadata(&checked) {
                Ok(metadata) => ensure!(
                    !metadata.file_type().is_symlink(),
                    "issue form path is a symlink"
                ),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                Err(error) => return Err(error.into()),
            }
        }
        if generate {
            fs::create_dir_all(destination.parent().context("form parent")?)?;
            fs::write(&destination, &expected)?;
        }
        ensure!(
            fs::read_to_string(&destination).with_context(|| format!("read {relative}"))?
                == expected,
            "{relative} is stale; run cargo xtask repository-forms generate"
        );
    }
    Ok(())
}

pub(crate) fn verify(repo: &Path, baseline: &str) -> Result<()> {
    if baseline == BASELINE {
        run(repo, false)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adaptations_preserve_complete_form_structure_and_requirements() {
        let source = "name: Bug Report\nlabels: [bug]\nbody:\n  - type: markdown\n    attributes:\n      value: https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md\n  - type: textarea\n    id: expected\n    attributes:\n      description: What did you expect Hunk to do instead?\n    validations:\n      required: false\n  - type: input\n    id: version\n    attributes:\n      description: e.g. output from `hunk --version` or the npm package version\n    validations:\n      required: true\n";
        let expected = source
            .replace("modem-dev/hunk", "ruttydm/workdeck")
            .replace("expect Hunk", "expect Workdeck")
            .replace(
                "`hunk --version` or the npm package version",
                "`workdeck --version` and the installation method",
            );
        let actual = adapt(source).unwrap();
        assert_eq!(actual, format!("{NOTICE}{expected}"));
        let parsed: serde_norway::Value = serde_norway::from_str(&actual).unwrap();
        assert_eq!(
            parsed["body"][1]["validations"]["required"].as_bool(),
            Some(false)
        );
        assert_eq!(
            parsed["body"][2]["validations"]["required"].as_bool(),
            Some(true)
        );
    }

    #[test]
    fn absent_duplicate_links_and_malformed_forms_are_rejected() {
        assert!(adapt("body: []").is_err());
        let link = "https://github.com/modem-dev/hunk/blob/main/CONTRIBUTING.md";
        assert!(adapt(&format!("body: []\n# {link}\n# {link}\n")).is_err());
        assert!(adapt(&format!("body: []\n# {link}\n")).is_err());
        assert!(adapt(&format!("body: [\n# {link}\n")).is_err());
    }
}
